-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Ystava CASCADE;
DROP TABLE IF EXISTS Tykkays CASCADE;
DROP TABLE IF EXISTS Ystavanetsija CASCADE;
DROP TABLE IF EXISTS Ystavanetsijan_Keskustelu CASCADE;
DROP TABLE IF EXISTS Keskustelu CASCADE;
DROP TABLE IF EXISTS Viesti CASCADE;
